package task2.action

object LibraryCommands {
   const val APPROVE_GIVING_BOOK_FOR_LIBRARY = "APPROVE_GIVING_BOOK_FOR_LIBRARY"
   const val APPROVE_GIVING_BOOK_FOR_HOME = "APPROVE_GIVING_BOOK_FOR_HOME"
   const val REJECT_GIVING_BOOK = "REJECT_GIVING_BOOK"
}